services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - red-monitoreo
    ports:
      - 9090:9090
  loki:
    image: grafana/loki:latest
    networks:
      - red-monitoreo
    ports:
      - 3100:3100
  alloy:
    image: grafana/alloy:latest
    networks:
      - red-monitoreo
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 12345:12345
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
  grafana:
    image: grafana/grafana:latest
    networks:
      - red-monitoreo
    ports:
      - 3000:3000

volumes:
  alloy_data:

networks:
  red-monitoreo:
    name: red-compartida-global
    external: true
